In [1]:
import pandas as pd
import os

source_path = "../data/"

dataframes = {}

for file in os.listdir(source_path):
    name = file.split(".")[0]
    ext = file.split(".")[1]

    if ext != "csv":
        continue

    df= pd.read_csv(source_path+file)
    dataframes[name] = df

    print(f"\nDataframe {name} successfully created")
    print(f"Created with {df.shape[0]} rows & {df.shape[1]} columns")

Dataframe recommendation_logs successfully created
Created with 52000 rows & 11 columns

Dataframe reviews successfully created
Created with 15450 rows & 12 columns

Dataframe users successfully created
Created with 10300 rows & 16 columns

Dataframe test successfully created
Created with 0 rows & 4 columns

Dataframe watch_history successfully created
Created with 105000 rows & 12 columns

Dataframe movies successfully created
Created with 1040 rows & 18 columns

Dataframe search_logs successfully created
Created with 26500 rows & 11 columns

In [2]:
# check columns
for name, df in dataframes.items():
    print(f"\n--{name}--\n", df.dtypes)

--recommendation_logs--
 recommendation_id        object
user_id                  object
movie_id                 object
recommendation_date      object
recommendation_type      object
recommendation_score    float64
was_clicked                bool
position_in_list          int64
device_type              object
time_of_day              object
algorithm_version        object
dtype: object

--reviews--
 review_id             object
user_id               object
movie_id              object
rating                 int64
review_date           object
device_type           object
is_verified_watch       bool
helpful_votes        float64
total_votes          float64
review_text           object
sentiment             object
sentiment_score      float64
dtype: object

--users--
 user_id                     object
email                       object
first_name                  object
last_name                   object
age                        float64
gender                      object
country                     object
state_province              object
city                        object
subscription_plan           object
subscription_start_date     object
is_active                     bool
monthly_spend              float64
primary_device              object
household_size             float64
created_at                  object
dtype: object

--test--
 test1    object
test2    object
test3    object
test4    object
dtype: object

--watch_history--
 session_id                 object
user_id                    object
movie_id                   object
watch_date                 object
device_type                object
watch_duration_minutes    float64
progress_percentage       float64
action                     object
quality                    object
location_country           object
is_download                  bool
user_rating               float64
dtype: object

--movies--
 movie_id                object
title                   object
content_type            object
genre_primary           object
genre_secondary         object
release_year             int64
duration_minutes       float64
rating                  object
language                object
country_of_origin       object
imdb_rating            float64
production_budget      float64
box_office_revenue     float64
number_of_seasons      float64
number_of_episodes     float64
is_netflix_original       bool
added_to_platform       object
content_warning           bool
dtype: object

--search_logs--
 search_id                   object
user_id                     object
search_query                object
search_date                 object
results_returned             int64
clicked_result_position    float64
device_type                 object
search_duration_seconds    float64
had_typo                      bool
used_filters                  bool
location_country            object
dtype: object

In [3]:
dataframes["users"].sample(10)

,user_id,email,first_name,last_name,age,gender,country,state_province,city,subscription_plan,subscription_start_date,is_active,monthly_spend,primary_device,household_size,created_at
6688,user_06689,justinthompson@example.org,Linda,Torres,35.0,Male,Canada,Saskatchewan,Villaborough,Premium,2022-12-30,True,6.11,Mobile,2.0,2024-12-05 15:24:11.469024
7042,user_07043,trodriguez@example.com,Vicki,Mason,28.0,NaN,Canada,Manitoba,East Scottview,Premium+,2024-09-08,True,24.47,Gaming Console,2.0,2023-02-23 16:57:19.761655
1576,user_01577,pfernandez@example.org,James,Lee,NaN,Female,USA,Washington,Port Douglasshire,Standard,2023-05-05,True,29.49,Desktop,4.0,2022-08-27 18:53:52.008389
4461,user_04462,gregoryanderson@example.org,Sean,Clayton,41.0,Female,Canada,Saskatchewan,East Emilyborough,Standard,2022-12-17,True,26.20,Desktop,2.0,2023-06-28 22:33:59.112980
410,user_00411,ntorres@example.net,Yvette,Ibarra,NaN,Male,USA,New York,East Maria,Basic,2025-01-02,True,NaN,Gaming Console,1.0,2023-11-17 21:50:20.758805
8284,user_08285,macdonaldsandra@example.net,Adam,Neal,44.0,Other,USA,Michigan,Port Laura,Standard,2024-07-18,True,9.33,Tablet,3.0,2024-10-29 11:16:10.978590
1611,user_01612,tavery@example.com,Madison,Nunez,21.0,Female,Canada,Newfoundland and Labrador,Mooreborough,Standard,2023-03-21,True,4.62,Smart TV,3.0,2023-06-08 20:24:11.740961
8506,user_08507,ueverett@example.com,Gregory,Morgan,40.0,Male,Canada,Quebec,Lisaville,Premium+,2022-09-13,True,23.50,Smart TV,1.0,2024-04-17 10:10:21.397029
9682,user_09683,elizabeth38@example.net,Mark,Gibson,55.0,Prefer not to say,Canada,British Columbia,Friedmantown,Standard,2024-08-21,False,21.53,Desktop,5.0,2025-01-03 15:01:41.177911
1551,user_01552,burnsshawn@example.org,Joseph,Rasmussen,22.0,Male,USA,Tennessee,Loriborough,Standard,2022-10-22,True,20.62,Gaming Console,1.0,2022-09-23 17:02:23.374297

In [4]:
dataframes["movies"].sample(10)

,movie_id,title,content_type,genre_primary,genre_secondary,release_year,duration_minutes,rating,language,country_of_origin,imdb_rating,production_budget,box_office_revenue,number_of_seasons,number_of_episodes,is_netflix_original,added_to_platform,content_warning
78,movie_0079,Mission Dream,Movie,War,NaN,2005,414.0,TV-G,Hindi,USA,5.9,4204348.0,24367896.0,NaN,NaN,False,2021-02-07,False
856,movie_0857,Day Warrior,Stand-up Comedy,Sport,Thriller,2011,61.0,R,English,Canada,3.7,NaN,NaN,NaN,NaN,False,2024-01-19,False
19,movie_0020,An Mystery,TV Series,Fantasy,NaN,2009,41.0,PG-13,English,Canada,7.1,NaN,NaN,14.0,168.0,False,2022-08-21,False
399,movie_0400,Night Queen,Movie,Action,NaN,2002,73.0,TV-MA,Korean,UK,NaN,179175.0,28601135.0,NaN,NaN,False,2024-05-29,False
328,movie_0329,Battle Phoenix,Stand-up Comedy,Documentary,NaN,2021,49.0,TV-Y7,English,USA,6.6,NaN,NaN,NaN,NaN,False,2025-07-25,True
734,movie_0735,Princess Hero,Documentary,Fantasy,Biography,2001,107.0,PG,German,USA,9.2,NaN,NaN,NaN,NaN,False,2024-04-01,True
858,movie_0859,First Mission,Documentary,Action,Western,2017,98.0,PG-13,English,USA,5.3,NaN,NaN,NaN,NaN,True,2022-06-24,True
185,movie_0186,Old House,TV Series,Comedy,NaN,1999,70.0,TV-G,English,USA,NaN,NaN,NaN,9.0,151.0,False,2024-03-08,True
357,movie_0358,Legend Secret,TV Series,Drama,NaN,1992,37.0,TV-MA,English,Japan,9.0,NaN,NaN,4.0,148.0,False,2025-04-21,False
128,movie_0129,Mission Fire,Stand-up Comedy,Sci-Fi,Crime,2000,36.0,TV-Y7,English,USA,NaN,NaN,NaN,NaN,NaN,True,2023-10-10,False

In [5]:
dataframes["reviews"].sample(10)

,review_id,user_id,movie_id,rating,review_date,device_type,is_verified_watch,helpful_votes,total_votes,review_text,sentiment,sentiment_score
7654,review_007655,user_02089,movie_0062,4,2025-12-20,Tablet,True,NaN,NaN,This movie exceeded my expectations.,positive,0.749
8144,review_008145,user_07967,movie_0419,4,2025-09-27,Laptop,False,4.0,10.0,Outstanding direction and screenplay.,positive,0.902
855,review_000856,user_01498,movie_0338,3,2025-08-10,Tablet,True,2.0,6.0,It was okay. Nothing special.,neutral,0.410
5351,review_005352,user_02548,movie_0640,5,2025-01-05,Tablet,True,2.0,4.0,One of the best series I've ever watched. High...,positive,0.976
11726,review_011727,user_09360,movie_0097,1,2024-02-23,Tablet,False,5.0,5.0,Overhyped. Didn't live up to expectations.,negative,0.322
13472,review_013473,user_05020,movie_0769,5,2025-02-25,Mobile,False,0.0,6.0,This movie exceeded my expectations.,positive,0.728
13697,review_013698,user_05793,movie_0863,3,2025-08-31,Laptop,True,9.0,9.0,Watchable but predictable.,neutral,0.460
10864,review_010865,user_04187,movie_0502,2,2025-06-13,Tablet,True,3.0,8.0,Slow paced and boring.,negative,0.329
1342,review_001343,user_07000,movie_0997,4,2025-12-26,Smart TV,False,5.0,8.0,Absolutely loved this movie. Great acting and ...,positive,0.797
2033,review_002034,user_00702,movie_0562,4,2024-08-31,Tablet,True,7.0,7.0,Absolutely loved this movie. Great acting and ...,positive,0.856

In [6]:
dataframes["recommendation_logs"].sample(10)

,recommendation_id,user_id,movie_id,recommendation_date,recommendation_type,recommendation_score,was_clicked,position_in_list,device_type,time_of_day,algorithm_version
41152,rec_041153,user_00969,movie_0708,2025-01-02,new_releases,0.404,False,6,Tablet,night,v1.3
30312,rec_030313,user_07350,movie_0758,2025-04-13,personalized,NaN,False,17,Smart TV,morning,v1.3
19757,rec_019758,user_07026,movie_0127,2024-12-31,trending,0.555,False,9,Smart TV,night,v1.4
44605,rec_044606,user_02817,movie_0138,2025-01-01,new_releases,0.295,False,8,Smart TV,night,v1.4
32475,rec_032476,user_00138,movie_0983,2024-03-16,genre_based,NaN,False,14,Smart TV,night,v2.0
10025,rec_010026,user_07530,movie_0560,2025-04-23,personalized,0.511,False,19,Mobile,afternoon,v1.4
41090,rec_041091,user_04140,movie_0758,2024-12-16,personalized,0.796,False,8,Smart TV,morning,v1.2
18600,rec_018601,user_01349,movie_0340,2025-10-05,similar_users,NaN,True,15,Mobile,evening,v1.3
41114,rec_041115,user_06639,movie_0319,2025-04-05,trending,0.850,False,3,Tablet,evening,v1.3
48134,rec_048135,user_03994,movie_0565,2025-02-27,new_releases,0.649,False,1,Smart TV,morning,v1.2

In [7]:
dataframes["search_logs"].sample(10)

,search_id,user_id,search_query,search_date,results_returned,clicked_result_position,device_type,search_duration_seconds,had_typo,used_filters,location_country
9648,search_009649,user_04329,music documentaries,2024-04-01,75,5.0,Mobile,13.5,False,False,Canada
12886,search_012887,user_09540,superhero movies,2025-07-01,38,NaN,Smart TV,23.7,False,False,USA
18287,search_018288,user_04336,drama series,2025-12-11,49,NaN,Laptop,32.1,True,False,USA
11909,search_011910,user_01441,classic movies,2025-03-18,35,4.0,Smart TV,45.9,False,False,Canada
21060,search_021061,user_08130,true crime,2025-10-16,60,NaN,Tablet,47.5,False,True,USA
2508,search_002509,user_09109,netflix originals,2025-11-20,94,NaN,Laptop,43.6,False,False,USA
13064,search_013065,user_09097,sci-fi,2024-10-19,25,NaN,Laptop,25.8,False,False,USA
17516,search_017517,user_05536,classic movies,2024-04-20,88,NaN,Tablet,8.1,False,False,USA
15238,search_015239,user_08630,war movies,2024-10-30,37,NaN,Tablet,24.8,False,False,USA
217,search_000218,user_03667,animated shows,2024-04-21,19,NaN,Laptop,50.4,False,False,USA

In [8]:
dataframes["watch_history"].sample(10)

,session_id,user_id,movie_id,watch_date,device_type,watch_duration_minutes,progress_percentage,action,quality,location_country,is_download,user_rating
67862,session_067863,user_01322,movie_0632,2024-02-19,Laptop,NaN,78.9,paused,HD,Canada,False,NaN
87902,session_087903,user_02381,movie_0461,2024-12-06,Laptop,69.4,22.3,paused,SD,USA,False,NaN
27486,session_027487,user_09253,movie_0844,2025-12-22,Smart TV,38.7,40.8,paused,HD,USA,False,NaN
98907,session_098908,user_06194,movie_0090,2025-05-07,Desktop,28.2,54.2,started,HD,USA,False,3.0
1180,session_001181,user_01623,movie_0648,2025-04-09,Smart TV,49.9,47.0,started,SD,USA,False,1.0
80260,session_080261,user_01595,movie_0370,2025-06-09,Smart TV,220.3,33.5,started,HD,Canada,False,NaN
77273,session_077274,user_05805,movie_0842,2024-10-29,Laptop,21.2,5.3,paused,4K,USA,False,NaN
65442,session_065443,user_02312,movie_0476,2025-01-21,Mobile,64.5,51.7,paused,4K,USA,False,NaN
104384,session_019095,user_05835,movie_0813,2025-11-25,Mobile,14.7,72.7,stopped,Ultra HD,USA,False,5.0
92252,session_092253,user_08187,movie_0545,2024-03-24,Desktop,24.7,60.7,completed,HD,USA,False,3.0

In [15]:
for name, df in dataframes.items():
    first_col = df.columns[0]
    dup_count = df[first_col].duplicated().sum()
    print(f"{name} duplicate counts (first column '{first_col}' only): {dup_count}")

recommendation_logs duplicate counts (first column 'recommendation_id' only): 2000
reviews duplicate counts (first column 'review_id' only): 450
users duplicate counts (first column 'user_id' only): 300
test duplicate counts (first column 'test1' only): 0
watch_history duplicate counts (first column 'session_id' only): 5000
movies duplicate counts (first column 'movie_id' only): 40
search_logs duplicate counts (first column 'search_id' only): 1500